
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author baser
 */
public class manageStudentsForm extends javax.swing.JFrame {

    /**
     * Creates new form manageStudentsForm
     */
    Student std=new Student();
             DefaultTableModel model;

    public manageStudentsForm() {
        initComponents();
        std.fillStudentJtable(jTable1, "");
        ButtonGroup bg=new ButtonGroup();//kadin erkek butonu birini sectiginde digerinin kapanmasi
        bg.add(jRadioButton_Male);
        bg.add(jRadioButton_female);
         model=(DefaultTableModel) jTable1.getModel();
         jTable1.setRowHeight(40);//tablo arasi genislik
        jTable1.setShowGrid(true);
         jTable1.setGridColor(Color.orange);//tablo cizgi renkleri
         jTable1.setSelectionBackground(Color.red);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Fname = new javax.swing.JTextField();
        jTextField_LName = new javax.swing.JTextField();
        jTextField_adres = new javax.swing.JTextField();
        jTextField_telefon = new javax.swing.JTextField();
        jRadioButton_Male = new javax.swing.JRadioButton();
        jRadioButton_female = new javax.swing.JRadioButton();
        jDateChooserBirthdata = new com.toedter.calendar.JDateChooser();
        JButton_Remowe = new javax.swing.JButton();
        JButtonEditStudent = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Val_Find = new javax.swing.JTextField();
        JButtonAddStudent1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_STD_ID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 102));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Cinsiyeti:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(23, 229, 132, 27);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Arama:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 80, 200, 27);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Soyadi:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(23, 172, 132, 27);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Dogum Tarihi:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(23, 286, 132, 27);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Telefon numarasi:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(23, 340, 132, 27);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Adres:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(23, 406, 132, 27);

        jTextField_Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FnameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_Fname);
        jTextField_Fname.setBounds(196, 114, 138, 27);

        jTextField_LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_LNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_LName);
        jTextField_LName.setBounds(196, 172, 138, 27);

        jTextField_adres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_adresActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_adres);
        jTextField_adres.setBounds(196, 394, 138, 55);

        jTextField_telefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telefonActionPerformed(evt);
            }
        });
        jTextField_telefon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telefonKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_telefon);
        jTextField_telefon.setBounds(196, 342, 138, 27);

        jRadioButton_Male.setText("Erkek");
        jRadioButton_Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_MaleActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_Male);
        jRadioButton_Male.setBounds(196, 234, 60, 21);

        jRadioButton_female.setText("Kadin");
        jRadioButton_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_femaleActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton_female);
        jRadioButton_female.setBounds(265, 234, 70, 21);
        jPanel1.add(jDateChooserBirthdata);
        jDateChooserBirthdata.setBounds(190, 290, 150, 30);

        JButton_Remowe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButton_Remowe.setText("Sil");
        JButton_Remowe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_RemoweActionPerformed(evt);
            }
        });
        jPanel1.add(JButton_Remowe);
        JButton_Remowe.setBounds(40, 500, 96, 29);

        JButtonEditStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButtonEditStudent.setText("Guncelle");
        JButtonEditStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonEditStudentActionPerformed(evt);
            }
        });
        jPanel1.add(JButtonEditStudent);
        JButtonEditStudent.setBounds(180, 500, 96, 29);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Adi:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(33, 120, 132, 27);

        jTextField_Val_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Val_FindActionPerformed(evt);
            }
        });
        jTextField_Val_Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_Val_FindKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Val_FindKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Val_FindKeyTyped(evt);
            }
        });
        jPanel1.add(jTextField_Val_Find);
        jTextField_Val_Find.setBounds(540, 80, 340, 27);

        JButtonAddStudent1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JButtonAddStudent1.setText("ekle");
        JButtonAddStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAddStudent1ActionPerformed(evt);
            }
        });
        jPanel1.add(JButtonAddStudent1);
        JButtonAddStudent1.setBounds(320, 500, 96, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Adi", "Soyadi", "Cinsiyet", "Dogum tarihi", "Telefon no", "adres"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 110, 540, 360);

        jTextField_STD_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_STD_IDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField_STD_ID);
        jTextField_STD_ID.setBounds(196, 69, 138, 27);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Id:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(92, 67, 33, 27);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FnameActionPerformed

    private void jTextField_LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_LNameActionPerformed

    private void jTextField_adresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_adresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_adresActionPerformed

    private void jTextField_telefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telefonActionPerformed

    }//GEN-LAST:event_jTextField_telefonActionPerformed

    private void jTextField_telefonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telefonKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_telefonKeyTyped
public boolean veriftexT (){
      if(jTextField_Fname.getText().equals("") || jTextField_LName.getText().equals("")||
              jTextField_telefon.getText().equals("") || jTextField_adres.getText().equals("") ||
              jTextField_STD_ID.getText().equals("")||jDateChooserBirthdata.getDate() == null){
          
           JOptionPane.showMessageDialog(null,"pne or more Empty field");
           return false;
      }
      //TARIHI SUAN2020 DEN FAZLA GOSTERIRSEK BU BILDIRIM CIKACAK
      else if(jDateChooserBirthdata.getDate().compareTo(new Date ()) > 0){
          JOptionPane.showMessageDialog(null,"no Dtudent from the futur this allowed");
          return false;
      }
      else{
         return true;   
      }
    
  }
 
    private void jRadioButton_MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_MaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_MaleActionPerformed

    private void jRadioButton_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton_femaleActionPerformed

    private void JButton_RemoweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_RemoweActionPerformed
       if(jTextField_STD_ID.getText().equals("")){
           JOptionPane.showMessageDialog(null, "ogrenci silinmedi ");
       }
       else{
        int id= Integer.valueOf(jTextField_STD_ID.getText());
         std.insertUpdateDeleteStudent('d', id, null, null, null, null, null, null);
       std.fillStudentJtable(jTable1, "");
       jTable1.setModel(new DefaultTableModel(null,new Object[]{"id","adi","soyadi","cinsiyet","dogum tarihi","telefon no","adres"}));
      std.fillStudentJtable(jTable1, jTextField_Val_Find.getText());
       MainForm.jLabel_StdCount.setText("Student Count= "+Integer.toString(MyFunction.countData(" student")));
       
       jTextField_STD_ID.setText("");
       jTextField_adres.setText("");
       jTextField_Fname.setText("");
       jTextField_LName.setText("");
       jTextField_telefon.setText("");
       jRadioButton_female.setSelected(false);
        jRadioButton_Male.setSelected(false);
        jDateChooserBirthdata.setDate(null);
       }
    }//GEN-LAST:event_JButton_RemoweActionPerformed
 
    private void JButtonEditStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonEditStudentActionPerformed
        String fname= jTextField_Fname.getText();
        String lname= jTextField_LName.getText();
        String phone= jTextField_telefon.getText();
        String address= jTextField_adres.getText();
        int id= Integer.valueOf(jTextField_STD_ID.getText());
        String sex="";
        if(jRadioButton_female.isSelected()){
            sex="Famele";
        }
        else if(jRadioButton_female.isSelected()){
            sex="Male";
        }
        if(veriftexT()){
            SimpleDateFormat dateFormat =new  SimpleDateFormat("yyyy-MM-dd");
            String bdate =dateFormat.format(jDateChooserBirthdata.getDate());
            Student std=new Student();
            std.insertUpdateDeleteStudent('u', id, fname, lname, sex, bdate, phone, address);
           // MainForm.jLabel_StdCount.setText("Student Count= "+Integer.toString(MyFunction.countData(" student")));
        }
    }//GEN-LAST:event_JButtonEditStudentActionPerformed

    private void jTextField_Val_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Val_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Val_FindActionPerformed

    private void JButtonAddStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAddStudent1ActionPerformed
       AddStudentForm addsf=new AddStudentForm();
                  addsf.setVisible(true);
                  addsf.pack();
                  addsf.setLocationRelativeTo(null);
                  addsf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_JButtonAddStudent1ActionPerformed
int rowIndex;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    //mouse bastiginda kaaytili kisileri aktariyor
        int rowIndex=jTable1.getSelectedRow();
       
        if(model.getValueAt(rowIndex, 3).toString().equals("Erkek")){
            jRadioButton_Male.setSelected(true);
             jRadioButton_female.setSelected(false);
        }
        else{
            jRadioButton_female.setSelected(true);
            jRadioButton_Male.setSelected(false);
        }
        jTextField_STD_ID.setText(model.getValueAt(rowIndex,0).toString());
        jTextField_Fname.setText(model.getValueAt(rowIndex,1).toString());
        jTextField_LName.setText(model.getValueAt(rowIndex,2).toString());
        jTextField_telefon.setText(model.getValueAt(rowIndex,5).toString());
        jTextField_adres.setText(model.getValueAt(rowIndex,6).toString());
        
        Date bdate;
        try {
            bdate=new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            jDateChooserBirthdata.setDate(bdate);
        } catch (ParseException ex) {
            Logger.getLogger(manageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_STD_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_STD_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_STD_IDActionPerformed

    private void jTextField_Val_FindKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Val_FindKeyTyped
   
    }//GEN-LAST:event_jTextField_Val_FindKeyTyped

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
         
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTextField_Val_FindKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Val_FindKeyPressed
        
    }//GEN-LAST:event_jTextField_Val_FindKeyPressed

    private void jTextField_Val_FindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Val_FindKeyReleased
      jTable1.setModel(new DefaultTableModel(null,new Object[]{"id","adi","soyadi","cinsiyet","dogum tarihi","telefon no","adres"}));
        std.fillStudentJtable(jTable1, jTextField_Val_Find.getText());
    }//GEN-LAST:event_jTextField_Val_FindKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
                int rowIndex=jTable1.getSelectedRow();
             jTextField_STD_ID.setText(model.getValueAt(rowIndex,0).toString());
        jTextField_Fname.setText(model.getValueAt(rowIndex,1).toString());
        jTextField_LName.setText(model.getValueAt(rowIndex,2).toString());
        jTextField_telefon.setText(model.getValueAt(rowIndex,5).toString());
        jTextField_adres.setText(model.getValueAt(rowIndex,6).toString());
        
          if(model.getValueAt(rowIndex, 3).toString().equals("Erkek")){
            jRadioButton_Male.setSelected(true);
             jRadioButton_female.setSelected(false);
        }
        else{
            jRadioButton_female.setSelected(true);
            jRadioButton_Male.setSelected(false);
        }
            Date bdate;
        try {
            bdate=new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 4).toString());
            jDateChooserBirthdata.setDate(bdate);
        } catch (ParseException ex) {
            Logger.getLogger(manageStudentsForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jTable1KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageStudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAddStudent1;
    private javax.swing.JButton JButtonEditStudent;
    private javax.swing.JButton JButton_Remowe;
    private com.toedter.calendar.JDateChooser jDateChooserBirthdata;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_Male;
    private javax.swing.JRadioButton jRadioButton_female;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_Fname;
    private javax.swing.JTextField jTextField_LName;
    private javax.swing.JTextField jTextField_STD_ID;
    private javax.swing.JTextField jTextField_Val_Find;
    private javax.swing.JTextField jTextField_adres;
    private javax.swing.JTextField jTextField_telefon;
    // End of variables declaration//GEN-END:variables
}
